---
- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: http
    package:
      name: httpie
      state: latest
  - name: install HAProxy
    yum:
      name=haproxy state=latest
  - name: enable HAProxy
    service:
      name: haproxy
      notify: restart_haproxy
  - name: configure haproxy
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
handlers: restart_haproxy
    service:
      name: haproxy
      state: restarted
