---
# file: site.yml
- import_playbook: config.yml
- import_playbook: deploy_haproxy.yml
- import_playbook: deploy_tomcat.yml
- import_playbook: deploy_web_content.yml
#- import_playbook: deploy_apache.yml
